# Generated by Django 5.2.4 on 2025-07-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='saved_for_later',
            field=models.BooleanField(default=False),
        ),
    ]
